apiVersion: v2
name: zeta-testenv
description: ZETA Guard test installation
type: application
version: 1.2.2
dependencies:
  - name: testfachdienst
    version: 0.0.1
    repository: file://charts/testfachdienst
    tags:
      - testfachdienst
  - name: hsmsim
    version: 0.0.1
    repository: file://charts/hsmsim
    condition: hsmsim.enabled
    tags:
      - hsmsim
  - name: popp-mocks
    version: 0.0.1
    repository: file://charts/popp-mocks
    condition: popp-mocks.enabled
    tags:
      - popp-mocks
  - name: test-monitoring-service
    version: 0.1.0
    repository: file://charts/test-monitoring-service
    alias: testMonitoringService
    condition: testMonitoringServiceEnabled
  - name: exauthsim
    version: 0.0.1
    repository: file://charts/exauthsim
    tags:
      - exauthsim
  - name: zeta-guard
    version: 1.2.2
    repository: file://charts/zeta-guard
    tags:
      - zeta-guard
  - name: testdriver
    version: 0.0.1
    repository: file://charts/test-driver
    tags:
      - testdriver
  - name: nativedriver
    version: 0.0.1
    repository: file://charts/native-driver
    tags:
      - nativedriver
  - name: tiger-proxy
    version: 0.0.1
    repository: file://charts/tiger-proxy
    tags:
      - tiger-proxy
  - name: tiger-testsuite
    version: 0.0.1
    repository: file://charts/tiger-testsuite
    tags:
      - tiger-testsuite
  - name: zeta-tls-test-tool-service
    version: 0.1.0
    repository: file://charts/zeta-tls-test-tool-service
    condition: zetaTlsTestToolServiceEnabled
  - name: zeta-cert-validation-mock
    version: 0.1.0
    repository: file://charts/zeta-cert-validation-mock
    condition: zetaCertValidationMockEnabled
  - name: infinispan-external
    version: 0.0.1
    repository: file://charts/infinispan-external
    tags:
      - infinispan-external
