{{- /* vim: set ft=helm: */ -}}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: pep-deployment
  labels:
    {{- include "pep-proxy.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.pepproxy.replicaCount }}
  selector:
    matchLabels:
      {{- include "pep-proxy.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "pep-proxy.labels" . | nindent 8 }}
        {{- with .Values.pepproxy.podLabels }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
      {{- if .Values.pepproxy.podAnnotations | or .Values.devMode | or .Values.pepproxy.nginxConf.generateConfigMap }}
      annotations:
        {{- with .Values.pepproxy.podAnnotations }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
        {{- if .Values.pepproxy.nginxConf.generateConfigMap }}
        {{- $nginxConf := include "zeta-guard.pep-nginx-conf" . }}
        checksum/nginx-conf: {{ $nginxConf | sha256sum }}
        {{- end }}
        {{- if .Values.devMode }}
        zeta.dev/rollout-timestamp: "{{ now | unixEpoch }}"
        {{- end }}
      {{- end }}
    spec:
      {{- if and .Values.pepproxy.serviceAccount .Values.pepproxy.serviceAccount.create }}
      serviceAccountName: {{ .Values.pepproxy.serviceAccount.name }}
      automountServiceAccountToken: false
      {{- end }}
      {{- with .Values.pepproxy.imagePullSecrets | default .Values.global.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.pepproxy.podSecurityContext }}
      securityContext:
        {{- toYaml . | nindent 8 }}
      {{- end }}
    {{- if .Values.global.enableDNSRedirect }}
      {{- template "global.tigerDNSRedirect" . }}
    {{- end }}
      {{- if .Values.pepproxy.asl_enabled }}
      initContainers:
        - name: trust-anchor-provisioning-processor
          image: "{{ include "provisioningProcessor.image" . | trim }}"
          imagePullPolicy: "{{ .Values.provisioningProcessor.imagePullPolicy }}"
          {{- with .Values.provisioningProcessor.containerSecurityContext }}
          securityContext:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          env:
            - name: RESULT_DIR
              value: "/var/trust-data"
            - name: PROCESSORS_ROOTS_JSON_ENABLED
              value: "true"
            - name: PROVISIONING_CONTAINER_NAME
              value: {{ .Values.provisioningProcessor.provisioningContainer | quote }}
            {{- include "zeta-guard.provisioningProcessor.caEnv" . | nindent 12 }}
            - name: TRUST_CERTCHAIN_FILE
              value: "/var/image-trustchain/certchain.pem"
            {{- include "zeta-guard.proxyEnvVars" .Values.global | nindent 12 }}
          {{- with .Values.provisioningProcessor.resources }}
          resources:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          volumeMounts:
            - name: trust-data
              mountPath: "/var/trust-data"
              readOnly: false
            - name: image-trustchain
              mountPath: "/var/image-trustchain"
              readOnly: true
            - name: tmpfs
              mountPath: "/tmp"
              readOnly: false
            {{- include "zeta-guard.provisioningProcessor.caVolumeMounts" . | nindent 12 }}
      {{- end }}
      containers:
        - name: nginx
          image: "{{ include "pep-proxy.image" . | trim }}"
          imagePullPolicy: "{{ .Values.pepproxy.imagePullPolicy }}"
          {{- $pepProxyEnvVars := include "zeta-guard.proxyEnvVars" .Values.global | trim }}
          {{- if or .Values.pepproxy.hsmProxyAddr $pepProxyEnvVars }}
          env:
            {{- with .Values.pepproxy.hsmProxyAddr }}
            - name: HSM_PROXY_ADDR
              value: {{ . }}
            {{- end }}
            {{- with $pepProxyEnvVars }}
            {{- . | nindent 12 }}
            {{- end }}
          {{- end }}
          ports:
            - name: http-main
              containerPort: 8081
            - name: status
              containerPort: 8080
          {{- if .Values.pepproxy.hsmProxyAddr }}
            - name: http-tls
              containerPort: 8443
          {{- end }}
          livenessProbe:
            httpGet:
              path: /status
              port: status
          readinessProbe:
            httpGet:
              path: /status
              port: status
          {{- if .Values.pepproxy.containerSecurityContext }}
          securityContext:
          {{- toYaml .Values.pepproxy.containerSecurityContext | nindent 12 }}
          {{- end }}
          startupProbe:
            httpGet:
              path: /status
              port: status
          {{- with .Values.pepproxy.resources }}
          resources:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          volumeMounts:
            - name: nginx-conf
              mountPath: /etc/nginx/nginx.conf
              subPath: nginx.conf
            {{- if .Values.pepproxy.asl_enabled }}
            - name: trust-data
              mountPath: "/var/trust-data"
              readOnly: true
            - name: asl-signer-cert
              mountPath: /etc/nginx/signer_cert.pem
              subPath: signer_cert.pem
              readOnly: true
            - name: asl-signer-key
              mountPath: /etc/nginx/signer_key.pem
              subPath: signer_key.pem
              readOnly: true
            - name: asl-issuer-cert
              mountPath: /etc/nginx/issuer_cert.pem
              subPath: issuer_cert.pem
              readOnly: true
            {{- end }}
            - name: nginx-cache
              mountPath: /var/cache/nginx
            - name: nginx-run
              mountPath: /var/run
            - name: tmp
              mountPath: /tmp
            {{- /* use subPath to only project intended files, not ..data etc. */ -}}
            {{- $files := .Files.Glob "files/well-known/*" }}
            {{- range $path, $_ := $files }}
            - name: well-known
              mountPath: /srv/.well-known/{{ base $path }}
              subPath: {{ base $path }}
            {{- end }}

      {{- if .Values.pepproxyMetricsEnabled }}
        - name: metrics
          image: "{{ .Values.pepproxyMetricsExporterImage }}"
          command:
            - nginx-prometheus-exporter
          args:
            - --nginx.scrape-uri=http://$(MY_POD_IP):8080/status
          env:
            - name: MY_POD_IP
              valueFrom:
                fieldRef:
                  fieldPath: status.podIP
          ports:
            - name: metrics
              containerPort: 9113
          livenessProbe:
            tcpSocket:
              port: metrics
          readinessProbe:
            httpGet:
              path: /metrics
              port: metrics
          startupProbe:
            httpGet:
              path: /metrics
              port: metrics
          {{- if .Values.pepproxy.containerSecurityContext }}
          securityContext:
          {{- toYaml .Values.pepproxy.containerSecurityContext | nindent 12 }}
          {{- end }}
          volumeMounts:
            - name: tmp
              mountPath: /tmp
      {{- end }}
      volumes:
        - name: nginx-conf
          configMap:
            name: "{{ .Values.pepproxy.nginxConf.configMapName }}"
            defaultMode: 0444
            items:
              - key: nginx.conf
                path: nginx.conf
        {{- if .Values.pepproxy.asl_enabled }}
        - name: trust-data
          emptyDir: {}
        - name: tmpfs
          emptyDir:
            medium: "Memory"
        - name: image-trustchain
          secret:
            secretName: {{ required "SecretRef for image verification certchain is missing, see imageTrustCertchainSecretRef" .Values.imageTrustCertchainSecretRef }}
        {{- include "zeta-guard.provisioningProcessor.caVolumes" . | nindent 8 }}
        - name: asl-signer-cert
          secret:
            secretName: asl-identity
            items:
              - key: signer-cert
                path: "signer_cert.pem"
        - name: asl-signer-key
          secret:
            secretName: asl-identity
            items:
              - key: signer-key
                path: "signer_key.pem"
        - name: asl-issuer-cert
          secret:
            secretName: asl-identity
            items:
              - key: issuer-cert
                path: "issuer_cert.pem"
        {{- end }}
        - name: nginx-cache
          emptyDir: {}
        - name: nginx-run
          emptyDir: {}
        - name: tmp
          emptyDir: {}
        - name: well-known
          configMap:
            name: pep-well-known
            defaultMode: 0444
      {{- with .Values.pepproxy.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.pepproxy.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}

---
{{- if .Values.pepproxy.nginxConf.generateConfigMap }}
{{- $nginxConf := include "zeta-guard.pep-nginx-conf" . }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: "{{ .Values.pepproxy.nginxConf.configMapName }}"
  labels:
    {{- include "pep-proxy.labels" . | nindent 4 }}
data:
  nginx.conf: |-
    {{- $nginxConf | nindent 4 }}
{{- end }}
---
apiVersion: v1
kind: Service
metadata:
  name: pep-proxy-svc
  labels:
    {{- include "pep-proxy.labels" . | nindent 4 }}
spec:
  selector:
    {{- include "pep-proxy.selectorLabels" . | nindent 4 }}
  ports:
    - name: http
      port: 80
      targetPort: http-main
    {{- if .Values.pepproxy.hsmProxyAddr }}
    - name: https
      port: 443
      targetPort: http-tls
    {{- end }}
    {{- if .Values.pepproxyMetricsEnabled }}
    - name: metrics
      port: 9113
      targetPort: metrics
    {{- end }}
  type: ClusterIP
