# Values for the umbrella chart (local environment with KIND)

global:
  registry_host: "europe-west3-docker.pkg.dev/gematik-pt-zeta-prod/zeta-dcr/"
  enableDNSRedirect: true

tags:
  exauthsim: true
  testfachdienst: true
  tiger-proxy: true
  tiger-testsuite: true
  zeta-guard: true
  zeta-tls-test-tool-service: true

zetaCertValidationMockEnabled: false

zeta-cert-validation-mock:
  devMode: true
  image:
    tag: 1.2.0
  mock:
    mode: always_good
    enableAdminEndpoints: true
  opentelemetry:
    enabled: true
    endpoint: http://telemetry-gateway-local:4318

hsmsim:
  enabled: true
  containerSecurityContext:
    allowPrivilegeEscalation: false
    readOnlyRootFilesystem: false
    runAsNonRoot: true
    runAsUser: 1000
    capabilities:
      drop: [ "ALL" ]

exauthsim:
  containerSecurityContext:
    allowPrivilegeEscalation: false
    readOnlyRootFilesystem: true
    runAsNonRoot: true
    runAsUser: 1000
    capabilities:
      drop: [ "ALL" ]
  devMode: true
  image:
    tag: 0.2.1

zetaTlsTestToolServiceEnabled: true

zeta-tls-test-tool-service:
  devMode: true
  image:
    tag: 1.2.0
  containerSecurityContext:
    allowPrivilegeEscalation: false
    readOnlyRootFilesystem: false
    runAsNonRoot: true
    runAsUser: 1000
    capabilities:
      drop: [ "ALL" ]
  service:
    type: NodePort
    nodePorts:
      serviceMgmtNodePort: 32012

zetaCertValidationMockEnabled: false

zeta-cert-validation-mock:
  devMode: true
  image:
    tag: 1.0.0
    repository:
  mock:
    mode: always_good
    enableAdminEndpoints: true

issuers:
  local:
    enabled: true
    issuerName: local-selfsigned
    certificateName: zeta-guard-local-tls
    secretName: zeta-guard-tls
    commonName: zeta-kind.local
    dnsNames:
      - zeta-kind.local
      - localhost
    duration: 8760h

popp-mocks:
  enabled: true
  containerSecurityContext:
    allowPrivilegeEscalation: false
    readOnlyRootFilesystem: true
    runAsNonRoot: true
    runAsUser: 1000
    capabilities:
      drop: [ "ALL" ]
  tokenGenerator:
    enabled: true
    ingress:
      enabled: true
      className: nginx
      hostname: zeta-kind.local

testdriver: &localDriver
  aslProdEnv: false
  connector_base_url: "http://exauthsim:80/ws"
  connector_card_handle: ""
  connector_client_system_id: ""
  connector_mandant_id: ""
  connector_user_id: ""
  connector_workspace_id: ""
  containerSecurityContext:
    allowPrivilegeEscalation: false
    readOnlyRootFilesystem: true
    runAsNonRoot: true
    runAsUser: 1000
    capabilities:
      drop: [ "ALL" ]
  devMode: true
  disableServerValidation: true
  fachdienst_url: "https://zeta-kind.local/pep/"
  hostname: zeta-kind.local
  image:
    tag: 1.2.2
  ingressClassName: nginx
  PoppToken: "eyJhbGciOiJFUzI1NiIsInR5cCI6InZuZC50ZWxlbWF0aWsucG9wcCtqd3QiLCJraWQiOiJhbGlhcyIsIng1YyI6WyJNSUlEQmpDQ0FxeWdBd0lCQWdJSEFtQ25LeHIvUnpBS0JnZ3Foa2pPUFFRREFqQ0JoREVMTUFrR0ExVUVCaE1DUkVVeEh6QWRCZ05WQkFvTUZtZGxiV0YwYVdzZ1IyMWlTQ0JPVDFRdFZrRk1TVVF4TWpBd0JnTlZCQXNNS1V0dmJYQnZibVZ1ZEdWdUxVTkJJR1JsY2lCVVpXeGxiV0YwYVd0cGJtWnlZWE4wY25WcmRIVnlNU0F3SGdZRFZRUUREQmRIUlUwdVMwOU5VQzFEUVRZeElGUkZVMVF0VDA1TVdUQWVGdzB5TlRBM01qZ3lNakF3TURCYUZ3MHpNREEzTWpneU1UVTVOVGxhTUdzeEN6QUpCZ05WQkFZVEFrUkZNU1l3SkFZRFZRUUtEQjFuWlcxaGRHbHJJRlJGVTFRdFQwNU1XU0F0SUU1UFZDMVdRVXhKUkRFME1ESUdBMVVFQXd3cmNHOXdjQzEwYjJ0bGJpNW5aVzFoZEdsckxuUmxiR1Z0WVhScGF5MTBaWE4wSUhOcGJYVnNZWFJ2Y2pCWk1CTUdCeXFHU000OUFnRUdDQ3FHU000OUF3RUhBMElBQkhBdkkzclBpTTRVNUhCekhUSXllc24vWmNaUkh0djlWeHVqbGJUYVJQdHYyc3FPNXZ5dmEyNEVRbjhBZ1M2bU9ObmVSaElJOHFoUkxxL1ZJMDZEeE9HamdnRWZNSUlCR3pBN0JnZ3JCZ0VGQlFjQkFRUXZNQzB3S3dZSUt3WUJCUVVITUFHR0gyaDBkSEE2THk5bGFHTmhMbWRsYldGMGFXc3VaR1V2WldOakxXOWpjM0F3SFFZRFZSME9CQllFRkRobnRHbnFueEVRTnpRdkRTTUpLSFllRUROYU1DRUdBMVVkSUFRYU1CZ3dDZ1lJS29JVUFFd0VnaDh3Q2dZSUtvSVVBRXdFZ1NNd0h3WURWUjBqQkJnd0ZvQVVuelhnTUtsL3l2aG1uNUFLUXMyN2dXV2ZTZjR3RGdZRFZSMFBBUUgvQkFRREFnWkFNRnNHQlNza0NBTURCRkl3VURCT01Fd3dTakJJTURvTU9GUnZhMlZ1TFZOcFoyNWhkSFZ5TFVsa1pXNTBhWFREcEhRZ1pzTzhjaUJRY205dlppQnZaaUJRWVhScFpXNTBJRkJ5WlhObGJtTmxNQW9HQ0NxQ0ZBQk1CSUpBTUF3R0ExVWRFd0VCL3dRQ01BQXdDZ1lJS29aSXpqMEVBd0lEU0FBd1JRSWhBS3VDdi9ZczBMd3lQRTh2eVBZWVF5UFpBTGltendwRjJHallVWUlwZ3QyNUFpQUhucVpubEV0dEhzL0Y0SEExckYyZWNmMjd0L2NMMlM4b0VvSFZaMmpra2c9PSJdfQ.eyJpYXQiOjE3ODI5MTEyODAsInZlcnNpb24iOiIxLjAuMCIsImlzcyI6Imh0dHBzOi8vcG9wcC5leGFtcGxlLmNvbSIsInByb29mTWV0aG9kIjoiZWhjLXByYWN0aXRpb25lci11c2VyLXg1MDkiLCJwYXRpZW50UHJvb2ZUaW1lIjoxNzgyOTA3NjgwLCJwYXRpZW50SWQiOiJYMTEwNjM5NDkxIiwiaW5zdXJlcklkIjoiMTA5NTAwOTY5IiwiYWN0b3JJZCI6IjEtMjAwMDAzMDAxMzkiLCJhY3RvclByb2Zlc3Npb25PaWQiOiIxLjIuMjc2LjAuNzYuNC4zMiJ9.Nf8oiNDg42rEACln6Or7rZoyHecH-IIKrxGsto3KklYE6GLb2Ea-m2ejH5im1Jx-u7SyxslZFCKm3LfPG7vVSw"
  routeViaTigerProxy: true
  smcbCertificateFileName: smcb-certificates.p12
  smcbCertificateAlias: zeta.c_smcb_aut
  requiredOid: "1.2.276.0.76.4.328"

nativedriver:
  <<: *localDriver

testfachdienst:
  containerSecurityContext:
    allowPrivilegeEscalation: false
    readOnlyRootFilesystem: true
    runAsNonRoot: true
    runAsUser: 1000
    capabilities:
      drop: [ "ALL" ]
  devMode: true
  env:
    - name: SERVER_SSL_ENABLED
      value: "true"
  image:
    tag: 1.2.0
  opentelemetry:
    enabled: true
    endpoint: http://telemetry-gateway-local:4318
    resourceAttributes:
      service.namespace: zeta-local
      service.version: 1.0.0
      deployment.environment.name: local

testMonitoringServiceEnabled: true

testMonitoringService:
  ingressRulesHost: "zeta-kind.local"
  opentelemetry-demo:
    grafana:
      resources:
        requests:
          cpu: 50m
          memory: 128Mi
        limits:
          cpu: 200m
          memory: 256Mi
    opentelemetry-collector:
      fullnameOverride: test-monitoring-collector-local
    prometheus:
      server:
        clusterRoleNameOverride: prometheus-local
        service:
          type: NodePort
          nodePort: 32090
    opensearch:
      protocol: http   # optional, but matches the demo’s http endpoint
      httpPort: 9200
      opensearchJavaOpts: "-Xms512m -Xmx512m"
      resources:
        requests:
          cpu: 250m
          memory: 1Gi
        limits:
          cpu: "1"
          memory: 2Gi
      service:
        type: NodePort
        nodePort: 32098

tiger-proxy:
  containerSecurityContext:
    allowPrivilegeEscalation: false
    readOnlyRootFilesystem: true
    runAsNonRoot: true
    runAsUser: 1000
    capabilities:
      drop: [ "ALL" ]
  devMode: true
  image:
    tag: 1.2.0
  proxyConfig:
    proxyRoutes:
      - from: /testfachdienst
        to: https://testfachdienst:443
      - from: /auth
        to: http://authserver/auth
      - from: /proxy
        to: http://testdriver/proxy
      - from: /opa
        to: http://opa:8181
      - from: /opa-simulation
        to: http://opa-simulation:8181
      - from: /.well-known/openid-federation
        to: http://popp-statics/.well-known/openid-federation
      - from: /.well-known/signed-jwks
        to: http://popp-statics/.well-known/signed-jwks
      - from: /popp
        to: http://popp-statics
#      - from: /ocsp/tls
#        to: http://zeta-cert-validation-mock/ocsp/tls
#      - from: /ocsp/smb
#        to: http://zeta-cert-validation-mock/ocsp/smb
      - from: /
        to: http://pep-proxy-svc
    tls:
      domainName: tiger-proxy
  service:
    type: NodePort
    nodePorts:
      admin: 32099
  startup:
    startupPeriodSeconds: 30

tiger-testsuite:
  containerSecurityContext:
    allowPrivilegeEscalation: false
    readOnlyRootFilesystem: true
    runAsNonRoot: true
    runAsUser: 1000
    capabilities:
      drop: [ "ALL" ]
  devMode: true
  env:
    zetaBaseUrl: zeta-kind.local
    zetaProxyUrl: zeta-kind.local:9999
    zetaProxy: proxy
    tigerEnvironment: cloud
    cucumberTags: ""
    mvnGoals: verify
    mvnAdditionalArgs: ""
    serenityExportDir: ""
  image:
    tag: 1.2.0
  proxyAdminService:
    enabled: true
    type: NodePort
    nodePort: 32011
  service:
    enabled: true
    type: NodePort
    port: 9010
    nodePort: 32010
  workflowUi:
    activateWorkflowUi: true
    trafficVisualization: true
    startBrowser: false
    workflowUiPort: 9010
    workflowUiStartTimeoutInSeconds: 300
    enableTestSelection: true
    runTestsOnStart: false
    tigerProxyConfiguration:
      adminPort: 9011

zeta-guard:
  authserver:
    admin:
      username: admin
      password: local-dev-password
    config:
      maxClients: "5000"
    genesisHash: 4841c2142fef441daa6ee6c57db65c011935964b14e94a6c8f5ec0447b83526c
    initContainer:
      containerSecurityContext:
        allowPrivilegeEscalation: false
        readOnlyRootFilesystem: true
        runAsNonRoot: true
        runAsUser: 1000
        capabilities:
          drop: [ "ALL" ]
    container:
      containerSecurityContext:
        allowPrivilegeEscalation: false
        readOnlyRootFilesystem: true
        runAsNonRoot: true
        runAsUser: 1000
        capabilities:
          drop: [ "ALL" ]
    hostname: zeta-kind.local
    hsm:
      enabled: true
      endpoint: "hsm-sim:50051"
      tls:
        enabled: true
        keyId: "zeta-guard-keycloak-tls-es256-v1.p256"
      tokenSigning:
        enabled: false
        keyId: "zeta-guard-keycloak-token-es256-v1.p256"
    image:
      tag: 1.2.3
    imagePullPolicy: IfNotPresent
    log:
      level: "INFO,de.gematik.zeta.zetaguard:debug"
    provider:
      smcB:
        # opaBaseUrl value has to be aligned with tags.tiger-proxy state
        # see docs/How_to_configure_tiger-proxy.md for reference
        opaBaseUrl: "http://tiger-proxy/opa"
        # opaBaseUrl: "http://opa:8181"
    smcbHashingPepper: 085c1245-dc0d-4d39-95b4-97496bec6182
    tls:
      enabled: false
      certSecretName: authserver-tls
  databaseMode: cloudnative
  devMode: true
  ingressClassName: nginx
  gematikConnectionEnabled: false
  nginx-ingress:
    controller:
      image:
        tag: 1.2.0
      ingressClass:
        name: nginx
      service:
        type: NodePort
        externalTrafficPolicy: Cluster
        httpPort:
          port: 80
          nodePort: 32080
          targetPort: 80
        httpsPort:
          port: 443
          nodePort: 32443
          targetPort: 443
    enabled: true
  opa:
    bundle:
      enabled: false
      serviceName: gar
      url: https://europe-west3-docker.pkg.dev
      resource: "<PROJECT_ID>/opa-bundles/zeta-authz:latest"
      verification:
        enabled: false
        keyId: signer
    containerSecurityContext:
      allowPrivilegeEscalation: false
      readOnlyRootFilesystem: true
      runAsNonRoot: true
      runAsUser: 1000
      capabilities:
        drop: [ "ALL" ]
    logLevel: info
    serviceAccountName: opa
    workloadIdentityFederation:
      enabled: false
      sts:
        audience: "//iam.googleapis.com/projects/<PROJECT_NUM>/locations/global/workloadIdentityPools/aks-pool/providers/aks-provider"
        tokenUrl: https://sts.googleapis.com/v1/token
      gar:
        host: europe-west3-docker.pkg.dev
  provisioningProcessor:
    image:
      tag: 1.2.0
    containerSecurityContext:
      allowPrivilegeEscalation: false
      readOnlyRootFilesystem: false
      runAsNonRoot: true
      runAsUser: 1000
      capabilities:
        drop: [ "ALL" ]
  pepproxy:
    asl_enabled: false
#    aslOcsp: "http://zeta-cert-validation-mock/ocsp"
    containerSecurityContext:
      allowPrivilegeEscalation: false
      readOnlyRootFilesystem: true
      runAsNonRoot: true
      runAsUser: 1000
      capabilities:
        drop: [ "ALL" ]
    image:
      tag: 1.2.0
    nginxConf:
      generateConfigMap: true
      pepIssuer: https://zeta-kind.local/auth/realms/zeta-guard
      requiredAudience: https://zeta-kind.local
    wellKnownBase: https://zeta-kind.local
  routeViaTigerProxy: true
  telemetryGatewayEnabled: true
  telemetry-gateway:
    command:
      name: /otelcol/zeta-telemetry-gateway
    fullnameOverride: telemetry-gateway-local
    securityContext:
      runAsNonRoot: true
      runAsUser: 1000
      allowPrivilegeEscalation: false
      readOnlyRootFilesystem: true
      capabilities:
        drop: [ "ALL" ]
    config:
      processors:
        batch:
          timeout: 60s
          send_batch_size: 1
      exporters:
        otlp_http/tms_dienst_hersteller:
          endpoint: http://test-monitoring-collector-local:4328
          encoding: json
          tls:
            insecure: true
        otlp_http/tms_gematik:
          endpoint: http://test-monitoring-collector-local:4338
          encoding: json
          tls:
            insecure: true
        otlp_http/tms_ti_siem:
          endpoint: http://test-monitoring-collector-local:4348
          encoding: json
          tls:
            insecure: true
      service:
        extensions:
          - health_check
        pipelines:
          logs/dienst_hersteller:
            exporters:
              - otlp_http/tms_dienst_hersteller

          logs/ti_sim:
            exporters:
              - otlp_http/tms_gematik

          logs/ti_siem:
            exporters:
              - count/siem
              - otlp_http/tms_ti_siem

          metrics/dienst_hersteller:
            exporters:
              - otlp_http/tms_dienst_hersteller

          metrics/ti_sim:
            exporters:
              - otlp_http/tms_gematik

          metrics/ti_siem:
            exporters:
              - otlp_http/tms_ti_siem

          traces/dienst_hersteller:
            exporters:
              - otlp_http/tms_dienst_hersteller

          traces/ti_sim:
            exporters:
              - otlp_http/tms_gematik

          traces/ti_siem:
            exporters:
              - otlp_http/tms_ti_siem
